[project]
name = "jobtools"
version = "1.0.0"
description = "Job Search Productivity Suite | Automate job discovery & manage your leads privately"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyside6>=6.10.1",
    "python-jobspy>=1.1.82",
    "qt-material>=2.17",
]
